Develop
mate-academy/js_calendar-table-DOM pull request #27
Opened 2020-04-14 13:08 UTC by crash2bash

2020-04-14 14:17 UTC, vpolets requested changes

2020-04-14 14:17 UTC, vpolets commented on src/scripts/main.js
> +               <th>ВС</th></tr></thead><tbody><tr>`;
та ну.. зроби заголовки циклом, кому треба ця ручна робота

2020-04-14 14:17 UTC, vpolets commented on src/scripts/main.js
> +               <th>ВС</th></tr></thead><tbody><tr>`;
та і помилитися набагато більша імовірність при такому підході

2020-04-14 14:17 UTC, vpolets commented on src/scripts/main.js
> +    for (let i = dayNumber(date); i <= 7; i++) {
що таке 7?

2020-04-15 07:33 UTC, denys-cheporniuk approved these changes

2023-03-22 09:03 UTC, closed without merging